
export const Product__Data = [
  {
    id: "BBQA",
    img: "/Images/Products/1.jpg",
    title: "BBQ",
    subTitle: "Premium Huddie",
    price: "119",
  },
  {
    id: "ADDIDAS",
    img: "/Images/Products/2.jpg",
    title: "ADDIDAS",
    subTitle: "Premium t'shirt",
    price: "99",
  },
  {
    id: "RODDIE",
    img: "/Images/Products/3.jpg",
    title: "RODDIE",
    subTitle: "Premium t'shirt",
    price: "59",
  },
  {
    id: "BeingHuman",
    img: "/Images/Products/4.jpg",
    title: "Being Human",
    subTitle: "Premium Huddie",
    price: "209",
  },
  {
    id: "Rostar",
    img: "/Images/Products/5.jpg",
    title: "Rostar",
    subTitle: "Premium t-shirt",
    price: "109",
  },
  {
    id: "CNT",
    img: "/Images/Products/6.jpg",
    title: "CNT",
    subTitle: "Premium t-shirt",
    price: "29",
  },
  {
    id: "Zaccky",
    img: "/Images/Products/7.jpg",
    title: "Zaccky",
    subTitle: "Premium t-shirt",
    price: "99",
  },
  {
    id: "Rock Star",
    img: "/Images/Products/8.jpg",
    title: "Rock Star",
    subTitle: "Premium t-shirt",
    price: "59",
  },
  {
    id: "Zarra",
    img: "/Images/Products/9.jpg",
    title: "Zarra",
    subTitle: "Premium jacket",
    price: "299",
  },
  {
    id: "Dry",
    img: "/Images/Products/10.jpg",
    title: "Dry",
    subTitle: "Premium t-shirt",
    price: "199",
  },
  {
    id: "Pumma",
    img: "/Images/Products/11.jpg",
    title: "Pumma",
    subTitle: "Premium t-shirt",
    price: "99",
  },
  
  {
    id: "Pumma2",
    img: "/Images/Products/12.jpg",
    title: "Pumma",
    subTitle: "Premium t-shirt",
    price: "99",
  },
  
  {
    id: "Rock Star2",
    img: "/Images/Products/13.jpg",
    title: "Rock Star",
    subTitle: "Premium t-shirt",
    price: "59",
  },
  {
    id: "ROSTARD",
    img: "/Images/Products/14.jpg",
    title: "ROSTARD",
    subTitle: "Premium t-shirt",
    price: "399",
  },
  {
    id: "SIMLLY1",
    img: "/Images/Products/15.jpg",
    title: "SIMPLY",
    subTitle: "Premium t-shirt",
    price: "299",
  },
  {
    id: "CA",
    img: "/Images/Products/16.jpg",
    title: "CA",
    subTitle: "Premium t-shirt",
    price: "199",
  },
  {
    id: "SIMPLY2",
    img: "/Images/Products/17.jpg",
    title: "SIMPLY",
    subTitle: "Premium t-shirt",
    price: "299",
  },
  {
    id: "LEVIS",
    img: "/Images/Products/18.jpg",
    title: "LEVIS",
    subTitle: "Premium t-shirt",
    price: "599",
  },
  {
    id: "LIVELIGHT",
    img: "/Images/Products/19.jpg",
    title: "LIVELIGHT",
    subTitle: "Premium t-shirt",
    price: "199",
  },
  {
    id: "SIMPLY3",
    img: "/Images/Products/20.jpg",
    title: "SIMPLY",
    subTitle: "Premium t-shirt",
    price: "299",
  },
  {
    id: "SIMPLY4",
    img: "/Images/Products/21.jpg",
    title: "SIMPLY",
    subTitle: "Premium t-shirt",
    price: "299",
  },
  {
    id: "ZARRA3",
    img: "/Images/Products/22.jpg",
    title: "ZARRA",
    subTitle: "Premium t-shirt",
    price: "399",
  },
  {
    id: "ZARRA4",
    img: "/Images/Products/23.jpg",
    title: "ZARRA",
    subTitle: "Premium t-shirt",
    price: "499",
  },
  {
    id: "SIMPLY5",
    img: "/Images/Products/24.jpg",
    title: "SIMPLY",
    subTitle: "Premium t-shirt",
    price: "199",
  },
  {
    id: "SIMPLY6",
    img: "/Images/Products/25.jpg",
    title: "SIMPLY",
    subTitle: "Premium t-shirt",
    price: "199",
  },
  {
    id: "SIMPLY7",
    img: "/Images/Products/26.jpg",
    title: "SIMPLY",
    subTitle: "Premium t-shirt",
    price: "199",
  },
  {
    id: "SIMPLY8",
    img: "/Images/Products/27.jpg",
    title: "SIMPLY",
    subTitle: "Premium t-shirt",
    price: "199",
  },
  {
    id: "ROSTARD3",
    img: "/Images/Products/28.jpg",
    title: "ROSTARD",
    subTitle: "Premium t-shirt",
    price: "399",
  },
  {
    id: "ROSTARD2",
    img: "/Images/Products/29.jpg",
    title: "ROSTARD",
    subTitle: "Premium t-shirt",
    price: "399",
  },
  {
    id: "ZACMA",
    img: "/Images/Products/30.jpg",
    title: "ZACMA",
    subTitle: "Premium t-shirt",
    price: "999",
  },
];
