
export const Product__Data = [
  {
    id: "Pumma",
    img: "/Images/Products/11.jpg",
    title: "Pumma",
    subTitle: "Premium t-shir",
    price: "99",
  },
  {
    id: "Zaccky",
    img: "/Images/Products/7.jpg",
    title: "Zaccky",
    subTitle: "Premium t-shir",
    price: "99",
  },
  {
    id: "PummaB",
    img: "/Images/Products/11.jpg",
    title: "Pumma",
    subTitle: "Premium t-shir",
    price: "99",
  },
  {
    id: "BeingHumanA",
    img: "/Images/Products/4.jpg",
    title: "Being Human",
    subTitle: "Premium Huddie",
    price: "209",
  },
  {
    id: "RostarA",
    img: "/Images/Products/5.jpg",
    title: "Rostar",
    subTitle: "Premium t-shirt",
    price: "109",
  },
  {
    id: "ZacckyB",
    img: "/Images/Products/7.jpg",
    title: "Zaccky",
    subTitle: "Premium t-shir",
    price: "99",
  },
  {
    id: "Rock StarA",
    img: "/Images/Products/8.jpg",
    title: "Rock Star",
    subTitle: "Premium t-shir",
    price: "59",
  },
  {
    id: "BBQA",
    img: "/Images/Products/1.jpg",
    title: "BBQ",
    subTitle: "Premium Huddie",
    price: "119",
  },
  {
    id: "Rock StarB",
    img: "/Images/Products/8.jpg",
    title: "Rock Star",
    subTitle: "Premium t-shir",
    price: "59",
  },
  {
    id: "ZarraA",
    img: "/Images/Products/9.jpg",
    title: "Zarra",
    subTitle: "Premium jacket",
    price: "299",
  },
  {
    id: "DryA",
    img: "/Images/Products/10.jpg",
    title: "Dry",
    subTitle: "Premium t-shir",
    price: "199",
  },
  {
    id: "PummaD",
    img: "/Images/Products/11.jpg",
    title: "Pumma",
    subTitle: "Premium t-shir",
    price: "99",
  },
  {
    id: "DryB",
    img: "/Images/Products/10.jpg",
    title: "Dry",
    subTitle: "Premium t-shir",
    price: "199",
  },
  {
    id: "PummaE",
    img: "/Images/Products/11.jpg",
    title: "Pumma",
    subTitle: "Premium t-shir",
    price: "99",
  },
  {
    id: "ZarraB",
    img: "/Images/Products/9.jpg",
    title: "Zarra",
    subTitle: "Premium jacket",
    price: "299",
  },
  {
    id: "Rock StarD",
    img: "/Images/Products/8.jpg",
    title: "Rock Star",
    subTitle: "Premium t-shir",
    price: "59",
  },
];
